name:                hasktorch-tools
version:             0.2.0.0
github:              DaisukeBekki/hasktorch-tools
license:             LGPL
author:              Daisuke Bekki and BekkiLab
maintainer:          bekki@is.ocha.ac.jp
copyright:           Daisuke Bekki and BekkiLab
synopsis:            Haskell Tools for Deep Learning via PyTorch
category:            Machine Learining
ghc-options:         -Wall
extra-source-files:
- README.md
- ChangeLog.md
description:         https://github.com/DaisukeBekki/hasktorch-tools#readme

dependencies:
 - base >= 4.7 && < 5
 - hasktorch >= 0.2
 - libtorch-ffi >= 1.4
 - libtorch-ffi-helper
 - codegen >= 0.1
 - async
 - finite-typelits
 - ghc-typelits-extra >= 0.3.1
 - ghc-typelits-knownnat >= 0.7
 - ghc-typelits-natnormalise >= 0.7
 - ghc-typelits-extra
 - ghc-typelits-knownnat
 - ghc-typelits-natnormalise
 - mtl
 - safe-exceptions
 - reflection
 - singletons
 - stm
 - JuicyPixels
 - vector
 - bytestring
 - safe-exceptions
 - zlib >= 0.6
 - gnuplot
 - text == 1.2.4.0
 - containers == 0.6.2.1
 - split == 0.2.3.4
 - filepath == 1.4.2.1
 - directory == 1.3.6.0
 - cereal == 0.5.8.1
 - cereal-text
 - juman-tools
 - matrix
 - random
 - vector
 - csv

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - MultiParamTypeClasses
  - RecordWildCards
  exposed-modules:
  - Torch.Control
  - Torch.Train
  - Torch.Layer.Linear
  - Torch.Layer.MLP
  - Torch.Layer.LSTM
  - Torch.Layer.BiLSTM
  - Torch.Tensor.TensorFactories
  - Torch.Tensor.Initializers
  - Torch.Util.Classification
  - Torch.Util.Dict
  - Torch.Util.Chart
  
executables:
  # test:
  #   main:                Main.hs
  #   source-dirs:         app/test
  #   ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  #   dependencies:
  #     - hasktorch-tools
  regression:
    main:         Main.hs
    source-dirs:  app/regression
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
  csvTraining:
    main:         Main.hs
    source-dirs:  app/csvTraining
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
#  getCovid19data:
#    main:                Main.hs
#    source-dirs:         app/covid19
#    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies:
##      - http-conduit >= 2.3
##      - req >= 3.1
#      - lens >= 0.4
#      - aeson >= 1.4
#      - aeson-lens >= 0.5
#      - bytestring
#  amazon-review:
#    main:                Main.hs
#    source-dirs:         app/amazon-review
#    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies:
#      - hasktorch-tools
#      - containers >= 0.6
tests:
  hasktorch-tools-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
